from oslo_log import log as logging

LOG = logging.getLogger(__name__)

ATTR_NOT_SPECIFIED = object()
UUID_LEN = 36
NAME_MAX_LEN = 255
INPUT_MAX_LEN = 1024
TENANT_ID_MAX_LEN = 36
IP_LEN = 15
TYPE_LEN = 20
STATUS_LEN = 2
TTL_LEN = 10
TYPES_LEN = 15
FIVE_LEN = 5
TEN_LEN = 10
SIXTYFOUR_LEN = 64
